version: '3.4'

services:
  meetingslime.api:
    image: ${DOCKER_REGISTRY-}meetingslimeapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Or Production based on your needs
      - ASPNETCORE_URLS=http://+:80;
    ports:
      - "8080:80"  # HTTP port
    volumes:
      - ./data:/app/data  # Mount the 'data' folder from host into '/app/data' inside container
